dist: trusty
install:
- pip install -r docs/requirements.txt
- git clone https://github.com/PurdueCAM2Project/CAM2Camera.wiki.git docs/sources
script:
- cd docs
- make html
- cd ..
cache: pip
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  github_token: $GITHUB_TOKEN
  on:
    all_branches: true
