language: python
python:
- '3.6'
dist: trusty
before_install:
- sudo apt-get install python-dev
- sudo apt-get install libpq-dev
- sudo apt-get install postgresql-9.5
- sudo apt-get install postgresql-contrib-9.5
- sudo apt-get install postgis-2.3

addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE cam2api;" -U postgres
- psql -c "CREATE USER cam2api WITH PASSWORD '123456';" -U postgres
- psql -c "\connect cam2api;" -U postgres
- psql -c "CREATE EXTENSION IF NOT EXISTS postgis;" -U postgres
- psql -c "\q"
script:
- travis_retry python manage.py makemigrations
- travis_retry python manage.py migrate
- travis_retry python manage.py test


