language: python
python:
- '3.6'
dist: trusty
before_install:
- sudo apt-get install python-dev
- sudo apt-get install libpq-dev
- sudo apt-get install postgresql
- sudo apt-get install postgresql-contrib
- sudo apt-get install postgis
- sudo apt-get install python3-pip
- sudo apt-get install python3-venv

install:
- pip install -r requirements.txt
script:
- travis_retry python manage.py test
cache: pip
